const $ = (selector) => document.querySelector(selector);
const results = $('#results');
const toast = (message) => { const el=$('#toast'); el.textContent=message; el.classList.add('show'); setTimeout(()=>el.classList.remove('show'),2600); };

fetch('/api/health').then(async response => {
  const data=await response.json(); if(!response.ok) throw new Error(data.error);
  $('#connection').textContent=data.version; $('#connection').classList.add('ok');
}).catch(error => { $('#connection').textContent='CLI unavailable'; $('#connection').title=error.message; });

$('#search-form').addEventListener('submit', async event => {
  event.preventDefault(); const params=new URLSearchParams(new FormData(event.currentTarget));
  $('#results-title').textContent=`Searching for “${params.get('q')}”…`; results.innerHTML='<div class="empty"><p>Searching your catalog…</p></div>';
  try { const response=await fetch(`/api/search?${params}`); const data=await response.json(); if(!response.ok) throw new Error(data.error); render(data.results || []); }
  catch(error){ results.innerHTML=`<div class="empty"><p>${escapeHTML(error.message)}</p></div>`; $('#results-title').textContent='Search unavailable'; }
});

function render(items){ $('#results-title').textContent=`${items.length} result${items.length===1?'':'s'}`; if(!items.length){results.innerHTML='<div class="empty"><p>No matches found. Try a broader search.</p></div>';return}
  results.innerHTML=items.map(item=>{const torrents=item.torrents||item.releases||[]; const title=item.title||item.name||'Untitled'; const rating=item.ratingImdb||item.ratingTmdb||item.rating; return `<article class="card"><div class="meta">${escapeHTML([item.contentType||item.type,item.year,rating&&`★ ${rating}`].filter(Boolean).join(' · '))}</div><h3>${escapeHTML(title)}</h3><p>${escapeHTML(item.overview||item.description||'')}</p><div class="releases">${torrents.slice(0,3).map(release=>{const hash=release.infoHash||release.info_hash||'';return `<div class="release"><b>${escapeHTML(release.quality||release.resolution||'Release')}</b><span>${escapeHTML(String(release.seeders??''))}${release.seeders!=null?' seeds':''}</span>${hash?`<button data-download="${escapeHTML(hash)}">Download</button><button class="stream" data-stream="${escapeHTML(hash)}" data-title="${escapeHTML(title)}">Stream</button>`:''}</div>`}).join('')}</div></article>`}).join('');
}
results.addEventListener('click',async event=>{const button=event.target.closest('[data-download]');if(!button)return;button.disabled=true;button.textContent='Starting…';try{const response=await fetch('/api/download',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({infoHash:button.dataset.download})});const data=await response.json();if(!response.ok)throw new Error(data.error);button.textContent='Started';toast('Download started in unarr');}catch(error){button.disabled=false;button.textContent='Download';toast(error.message)}});
let streamSession=null, streamPoll=null;
results.addEventListener('click',async event=>{const button=event.target.closest('[data-stream]');if(!button)return;button.disabled=true;const dialog=$('#player-dialog');$('#player-title').textContent=button.dataset.title;renderStreamProgress({phase:'metadata',message:'Starting unarr…',elapsedSeconds:0,metadataTimeoutSeconds:60});dialog.showModal();try{const response=await fetch('/api/stream',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({infoHash:button.dataset.stream})});const data=await response.json();if(!response.ok)throw new Error(data.error);streamSession=data.id;pollStream();}catch(error){renderStreamError(error.message);button.disabled=false;}});
async function pollStream(){clearTimeout(streamPoll);if(!streamSession)return;try{const response=await fetch(`/api/stream/${encodeURIComponent(streamSession)}`);const data=await response.json();if(!response.ok)throw new Error(data.error);if(data.status==='ready'&&data.url){$('#player-stage').innerHTML=`<video controls autoplay playsinline src="${escapeHTML(data.url)}"></video>`;return}if(data.status==='error')throw new Error(data.error||'Stream failed.');if(data.status==='stopped')throw new Error('Stream stopped before playback became ready.');renderStreamProgress(data);streamPoll=setTimeout(pollStream,1000);}catch(error){renderStreamError(error.message);}};
function renderStreamProgress(data){const metadata=data.phase==='metadata';const elapsed=data.elapsedSeconds||0;const timeout=data.metadataTimeoutSeconds||60;const percent=metadata?Math.min(100,Math.round(elapsed/timeout*100)):(data.progress||0);const detail=metadata?`Metadata deadline: ${elapsed}s of ${timeout}s`:data.message;$('#player-stage').innerHTML=`<div class="stream-progress"><div class="spinner"></div><strong>${escapeHTML(data.message||'Preparing stream…')}</strong><span>${escapeHTML(detail)}</span><div class="progress-track"><i style="width:${percent}%"></i></div>${metadata?'<small>If no peers provide metadata within 60 seconds, unarr will stop this attempt.</small>':''}</div>`;}
function renderStreamError(message){$('#player-stage').innerHTML=`<div class="stream-error"><strong>Couldn’t start playback</strong><span>${escapeHTML(message)}</span><small>Try a release with more seeders or choose another quality.</small></div>`;}
async function closePlayer(){clearTimeout(streamPoll);const id=streamSession;streamSession=null;$('#player-dialog').close();$('#player-stage').innerHTML='';document.querySelectorAll('[data-stream]:disabled').forEach(button=>button.disabled=false);if(id)await fetch(`/api/stream/${encodeURIComponent(id)}`,{method:'DELETE'}).catch(()=>{});} $('#close-player').addEventListener('click',closePlayer); $('#player-dialog').addEventListener('cancel',event=>{event.preventDefault();closePlayer()});
$('#status-button').addEventListener('click',async()=>{const dialog=$('#status-dialog');dialog.showModal();$('#status-output').textContent='Loading…';try{const response=await fetch('/api/status');const data=await response.json();if(!response.ok)throw new Error(data.error);$('#status-output').textContent=data.output}catch(error){$('#status-output').textContent=error.message}}); $('#close-dialog').addEventListener('click',()=>$('#status-dialog').close());
function escapeHTML(value){return String(value??'').replace(/[&<>'"]/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[char]))}
