const $ = (selector) => document.querySelector(selector);
const results = $('#results');
let libraryItems=[];
let currentView='discover', libraryTimer=null,librarySearchTimer=null,librarySourceFilter='all',libraryActionItem=null,libraryActionGroup=null,libraryHoldTimer=null,suppressLibraryClick=false,libraryTotal=0,libraryVisibleLimit=250,libraryGroups=[],libraryAutoMatching=false,libraryAutoMatchBudget=12,aiConfigured=false;
let librarySignature='';
let traktAuthTimer=null;
let traktSearchTimer=null,traktSearchRequest=0;
let activityTimer=null,currentReleaseTitle='',currentReleaseMedia=null,currentTraktDetail=null,currentTargetEpisode=null;
let posterActionItem=null,posterHoldTimer=null,suppressPosterClick=false;
const toast = (message) => { const el=$('#toast'); el.textContent=message; el.classList.add('show'); setTimeout(()=>el.classList.remove('show'),2600); };

loadTraktDashboard();

async function loadTraktDashboard(){
  const dashboard=$('#trakt-dashboard');
  try{
    const response=await fetch('/api/trakt/dashboard');
    const data=await response.json();
    if(!response.ok)throw new Error(data.error);
    dashboard.innerHTML=`${!data.configured?`<div class="trakt-setup"><strong>Connect Trakt</strong><span>${escapeHTML(data.message||'Configure Trakt to load these shelves.')}</span></div>`:''}${(data.sections||[]).map(renderTraktSection).join('')}`;
  }catch(error){dashboard.innerHTML=`<div class="trakt-setup"><strong>Trakt is unavailable</strong><span>${escapeHTML(error.message)}</span></div>`;}
}

function renderTraktSection(section){
  const items=section.items||[];
  const status=section.locked?'Connect Trakt':section.error?'Unavailable':'';
  const cards=items.length?items.map(item=>{const detail=item.ids?.trakt&&['movie','show'].includes(item.mediaType)?`data-trakt-id="${escapeHTML(item.ids.trakt)}" data-trakt-type="${escapeHTML(item.mediaType)}" data-trakt-title="${escapeHTML(item.title)}" data-watchlisted="${item.watchlisted?'1':'0'}" data-season="${escapeHTML(item.season??'')}" data-episode="${escapeHTML(item.episode??'')}"`:'';const identifiers=[item.watchState==='watched'&&'<span class="poster-identifier watched">✓ Watched</span>',item.watchState==='in-progress'&&'<span class="poster-identifier progress">▶ In progress</span>',item.watchlisted&&'<span class="poster-identifier watchlist">＋ Watchlist</span>'].filter(Boolean).join('');return `<button class="trakt-card" ${detail} aria-label="View ${escapeHTML(item.title)} details">${item.image?`<img src="${escapeHTML(item.image)}" alt="" loading="lazy" draggable="false">`:''}<span class="trakt-shade"></span>${identifiers?`<span class="poster-identifiers">${identifiers}</span>`:''}<span class="trakt-card-copy"><b>${escapeHTML(item.title)}</b><small>${escapeHTML([item.calendarAt&&formatCalendarDate(item.calendarAt),item.year,item.rating&&`★ ${Number(item.rating).toFixed(1)}`].filter(Boolean).join(' · '))}</small></span>${item.progress!=null?`<progress class="trakt-progress" max="100" value="${Math.max(0,Math.min(100,Number(item.progress)||0))}"></progress>`:''}</button>`}).join(''):`<div class="trakt-placeholder"><span>${escapeHTML(section.error||status||'Nothing here yet')}</span></div>`;
  return `<section class="trakt-row"><div class="trakt-row-head"><h2>${escapeHTML(section.title)}</h2><div>${status?`<span>${escapeHTML(status)}</span>`:''}${items.length>0?`<button class="see-all" type="button">See all</button>`:''}</div></div><div class="trakt-strip">${cards}</div></section>`;
}

$('#trakt-dashboard').addEventListener('click',event=>{const expand=event.target.closest('.see-all');if(expand){const row=expand.closest('.trakt-row');row.classList.toggle('expanded');expand.textContent=row.classList.contains('expanded')?'Show less':'See all';return}const card=event.target.closest('[data-trakt-id]');if(card){if(suppressPosterClick){suppressPosterClick=false;return}openTraktDetails(card.dataset.traktType,card.dataset.traktId,card.dataset.season,card.dataset.episode)}});
function openPosterActions(card){posterActionItem={type:card.dataset.traktType,id:Number(card.dataset.traktId),title:card.dataset.traktTitle,watchlisted:card.dataset.watchlisted==='1',season:card.dataset.season,episode:card.dataset.episode};$('#poster-action-title').textContent=posterActionItem.title;$('#poster-watchlist-action').textContent=posterActionItem.watchlisted?'Remove from watchlist':'Add to watchlist';$('#poster-actions').showModal()}
$('#trakt-dashboard').addEventListener('pointerdown',event=>{const card=event.target.closest('.trakt-card[data-trakt-id]');if(!card)return;clearTimeout(posterHoldTimer);posterHoldTimer=setTimeout(()=>{suppressPosterClick=true;navigator.vibrate?.(30);openPosterActions(card)},550)});
for(const name of ['pointerup','pointercancel','pointerleave'])$('#trakt-dashboard').addEventListener(name,()=>clearTimeout(posterHoldTimer));
$('#trakt-dashboard').addEventListener('pointermove',event=>{if(Math.abs(event.movementX)>3||Math.abs(event.movementY)>3)clearTimeout(posterHoldTimer)});
$('#trakt-dashboard').addEventListener('contextmenu',event=>{const card=event.target.closest('.trakt-card[data-trakt-id]');if(!card)return;event.preventDefault();suppressPosterClick=true;openPosterActions(card)});
$('#close-poster-actions').addEventListener('click',()=>$('#poster-actions').close());
$('#poster-actions').addEventListener('click',event=>{if(event.target===event.currentTarget)event.currentTarget.close()});
$('#poster-watchlist-action').addEventListener('click',async()=>{if(!posterActionItem)return;const button=$('#poster-watchlist-action');button.disabled=true;try{const action=posterActionItem.watchlisted?'remove':'add';await postJSON('/api/trakt/watchlist',{action,type:posterActionItem.type,traktId:posterActionItem.id});$('#poster-actions').close();toast(`${posterActionItem.title} ${action==='add'?'added to':'removed from'} watchlist`);await loadTraktDashboard()}catch(error){alert(`Could not update watchlist:\n\n${error.message}`)}finally{button.disabled=false}});
$('#poster-download-action').addEventListener('click',async()=>{if(!posterActionItem)return;const item=posterActionItem;$('#poster-actions').close();if(item.type==='show'){openTraktDetails(item.type,item.id,item.season,item.episode);toast('Choose an episode for download options');return}try{const detail=await fetchTraktDetails(item.type,item.id);openReleasePicker({type:'movie',title:detail.title,traktId:item.id,imdbId:detail.ids?.imdb||null,tmdbId:detail.ids?.tmdb||null},detail.title)}catch(error){alert(`Could not load download options:\n\n${error.message}`)}});

async function openTraktDetails(type,id,season,episode){const dialog=$('#title-dialog');$('#title-detail').innerHTML='<div class="detail-loading">Loading Trakt metadata…</div>';dialog.showModal();try{const data=await fetchTraktDetails(type,id);const targetSeason=season!==''&&season!=null?Number(season):null;currentTargetEpisode=episode!==''&&episode!=null?Number(episode):null;if(targetSeason!=null&&data.seasons){data.seasons.sort((a,b)=>(a.number===targetSeason?-1:b.number===targetSeason?1:0))}currentTraktDetail=data;renderTitleDetail(data)}catch(error){$('#title-detail').innerHTML=`<div class="detail-loading">${escapeHTML(error.message)}</div>`}}
async function fetchTraktDetails(type,id,season){const params=new URLSearchParams({type,id});if(season!=null)params.set('season',season);const response=await fetch(`/api/trakt/details?${params}`);const data=await response.json();if(!response.ok)throw new Error(data.error);return data}
function renderTitleDetail(data){const facts=[data.year,data.certification,data.runtime&&`${data.runtime} min`,data.rating&&`★ ${Number(data.rating).toFixed(1)}`,data.status,data.network].filter(Boolean);const seasons=data.seasons||[],defaultSeason=seasons.find(season=>season.number>0)?.number??seasons[0]?.number;const playData=`data-play-type="${escapeHTML(data.mediaType)}" data-play-title="${escapeHTML(data.title)}" data-play-imdb="${escapeHTML(data.ids?.imdb||'')}" data-play-tmdb="${escapeHTML(data.ids?.tmdb||'')}"`;$('#title-detail').innerHTML=`${data.fanart?`<img class="detail-backdrop" src="${escapeHTML(data.fanart)}" alt="">`:''}<div class="detail-shade"></div><div class="detail-body">${data.poster?`<img class="detail-poster" src="${escapeHTML(data.poster)}" alt="${escapeHTML(data.title)} poster">`:''}<div class="detail-copy"><p class="eyebrow">${escapeHTML(data.mediaType)}</p><h2>${escapeHTML(data.title)}</h2>${data.tagline?`<p class="detail-tagline">${escapeHTML(data.tagline)}</p>`:''}<div class="detail-facts">${facts.map(value=>`<span>${escapeHTML(value)}</span>`).join('')}</div><button class="play-from-detail" ${playData} ${seasons.length?'data-play-season="0" data-play-episode="1"':''}>${seasons.length?'Play series':'Play movie'}</button><p class="detail-overview">${escapeHTML(data.overview||'No overview available.')}</p>${data.genres?.length?`<div class="detail-genres">${data.genres.map(value=>`<span>${escapeHTML(value)}</span>`).join('')}</div>`:''}${seasons.length?`<label class="season-picker">Season<select id="season-select">${seasons.map(season=>`<option value="${season.number}" ${season.number===defaultSeason?'selected':''}>${escapeHTML(season.title)}${season.episodeCount?` · ${season.episodeCount} episodes`:''}</option>`).join('')}</select></label><div id="episodes" class="episodes"><div class="detail-loading">Loading episodes…</div></div>`:''}</div></div>`;if(seasons.length){const select=$('#season-select');const play=$('.play-from-detail');play.dataset.playSeason=select.value;play.textContent=`Play Season ${select.value}`;select.addEventListener('change',()=>{play.dataset.playSeason=select.value;play.textContent=`Play Season ${select.value}`;loadSeason(data,select.value)});loadSeason(data,select.value)}}
async function loadSeason(show,season){const target=$('#episodes');target.innerHTML='<div class="detail-loading">Loading episodes…</div>';try{const data=await fetchTraktDetails(show.mediaType,String(show.ids.trakt),season);const episodes=data.episodes||[];target.innerHTML=episodes.length?episodes.map(episode=>`<article class="episode-card">${episode.image?`<img src="${escapeHTML(episode.image)}" alt="" loading="lazy">`:''}<div><b>${episode.number}. ${escapeHTML(episode.title)}</b><small>${escapeHTML([episode.runtime&&`${episode.runtime} min`,episode.firstAired&&formatCalendarDate(episode.firstAired),episode.rating&&`★ ${Number(episode.rating).toFixed(1)}`].filter(Boolean).join(' · '))}</small><p>${escapeHTML(episode.overview||'')}</p><button class="episode-play" data-play-type="show" data-play-title="${escapeHTML(show.title)} S${season}E${episode.number}" data-play-imdb="${escapeHTML(show.ids?.imdb||'')}" data-play-tmdb="${escapeHTML(show.ids?.tmdb||'')}" data-play-season="${season}" data-play-episode="${episode.number}">Play episode</button></div></article>`).join(''):'<div class="detail-loading">No episodes found.</div>'}catch(error){target.innerHTML=`<div class="detail-loading">${escapeHTML(error.message)}</div>`}}
$('#title-detail').addEventListener('click',event=>{const button=event.target.closest('[data-play-type]');if(!button)return;const body={type:button.dataset.playType,title:button.dataset.playTitle,traktId:Number(currentTraktDetail?.ids?.trakt)||null,imdbId:button.dataset.playImdb||null,tmdbId:button.dataset.playTmdb||null};if(body.type==='show'){body.season=Number(button.dataset.playSeason);body.episode=Number(button.dataset.playEpisode)}$('#title-dialog').close();openReleasePicker(body,button.dataset.playTitle)});
$('#close-title-dialog').addEventListener('click',()=>$('#title-dialog').close());$('#title-dialog').addEventListener('click',event=>{if(event.target===event.currentTarget)event.currentTarget.close()});
new MutationObserver(()=>{if(currentTargetEpisode==null)return;const button=document.querySelector(`#episodes [data-play-episode="${currentTargetEpisode}"]`);if(button){const card=button.closest('.episode-card');card?.classList.add('target-episode');card?.scrollIntoView({block:'center',behavior:'smooth'});currentTargetEpisode=null}}).observe($('#title-detail'),{childList:true,subtree:true});

async function openReleasePicker(body,title){currentReleaseTitle=title;currentReleaseMedia=body;const dialog=$('#release-dialog');$('#release-title').textContent=title;$('#release-results').innerHTML='<div class="detail-loading">Checking TorrentClaw and hosted debrid caches…</div>';dialog.showModal();try{const data=await postJSON('/api/torrentclaw/releases',body);renderReleases(data)}catch(error){$('#release-results').innerHTML=`<div class="detail-loading">${escapeHTML(error.message)}</div>`}}
function releaseCard(release,data){const torrentClaw=release.sourceGroup==='torrentclaw',ids=`data-torrent-id="${escapeHTML(release.torrentId??'')}" data-file-id="${escapeHTML(release.fileId??'')}" data-file-name="${escapeHTML(release.rawTitle||'')}"`;return `<article class="release-choice ${release.instant?'instant':''}"><div><div class="release-badges">${release.instant?`<strong>INSTANT · ${escapeHTML(release.debridProvider)}</strong>`:''}<span>${escapeHTML(release.quality||'Unknown quality')}</span>${release.hdrType?`<span>${escapeHTML(release.hdrType)}</span>`:''}</div><h3>${escapeHTML(release.rawTitle||'Torrent release')}</h3><p>${escapeHTML([release.codec,release.sourceType,release.sizeBytes&&formatBytes(release.sizeBytes),`${release.seeders||0} seeds`].filter(Boolean).join(' · '))}</p></div><div class="release-actions">${release.instant?`<button data-debrid-play="${escapeHTML(release.infoHash)}" ${ids}>Play from TorBox</button>`:''}${data.debridConfigured&&(!release.instant||torrentClaw)?`<button class="secondary" data-debrid-download="${escapeHTML(release.infoHash)}">Download to TorBox</button>`:''}${torrentClaw?`<button class="secondary" data-local-download="${escapeHTML(release.infoHash)}">Download locally</button>`:''}</div></article>`}
function renderReleases(data){const groups=data.groups||[{title:'Results',releases:data.releases||[]}];const total=groups.reduce((count,group)=>count+(group.releases||[]).length,0);$('#release-results').innerHTML=total?groups.map(group=>`<section class="release-group"><div class="release-group-head"><h3>${escapeHTML(group.title)}</h3><span>${(group.releases||[]).length}</span></div>${(group.releases||[]).length?(group.releases||[]).map(release=>releaseCard(release,data)).join(''):'<p class="release-empty">No matching sources.</p>'}</section>`).join(''):'<div class="detail-loading">No playable releases found.</div>'}
$('#close-release-dialog').addEventListener('click',()=>$('#release-dialog').close());
$('#release-results').addEventListener('click',async event=>{const button=event.target.closest('[data-debrid-play],[data-debrid-download],[data-local-download]');if(!button)return;button.disabled=true;try{if(button.dataset.debridPlay){const body={infoHash:button.dataset.debridPlay,fileName:button.dataset.fileName||''};if(button.dataset.torrentId)body.torrentId=Number(button.dataset.torrentId);if(button.dataset.fileId!=='')body.fileId=Number(button.dataset.fileId);const response=await postJSON('/api/torrentclaw/debrid/play',body);if(!response.id)throw new Error('TorBox did not return a playable stream session.');location.href=playerPath(response.id);return}const local=button.dataset.localDownload;await postJSON(local?'/api/download':'/api/torrentclaw/debrid/download',{infoHash:local||button.dataset.debridDownload});button.textContent='Queued';await refreshActivity(true)}catch(error){button.disabled=false;alert(`Could not start this source:\n\n${error.message}`)}});
function playerPath(session){const params=new URLSearchParams({session,title:currentReleaseTitle});if(currentReleaseMedia?.traktId){params.set('traktType',currentReleaseMedia.type);params.set('traktId',currentReleaseMedia.traktId);params.set('imdbId',currentReleaseMedia.imdbId||'');params.set('tmdbId',currentReleaseMedia.tmdbId||'');if(currentReleaseMedia.type==='show'){params.set('showTitle',currentReleaseMedia.title.replace(/\s+S\d+E\d+$/i,''));params.set('season',currentReleaseMedia.season);params.set('episode',currentReleaseMedia.episode)}}return `/watch.html?${params}`}
async function postJSON(endpoint,body){const response=await fetch(endpoint,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const data=await response.json();if(!response.ok)throw new Error(data.error);return data}

fetch('/api/health').then(async response => {
  const data=await response.json(); if(!response.ok) throw new Error(data.error);
  $('#connection').textContent=data.version; $('#connection').classList.add('ok');
}).catch(error => { $('#connection').textContent='CLI unavailable'; $('#connection').title=error.message; });

$('#search-form').addEventListener('submit',event=>{event.preventDefault();loadTraktMatches($('#query').value.trim())});
$('#query').addEventListener('input',event=>{clearTimeout(traktSearchTimer);const query=event.target.value.trim();if(query.length<2){$('#trakt-search-results').hidden=true;return}traktSearchTimer=setTimeout(()=>loadTraktMatches(query),250)});
async function loadTraktMatches(query){if(query.length<2)return;const requestId=++traktSearchRequest;const target=$('#trakt-search-results');target.hidden=false;target.innerHTML='<div class="search-match-state">Searching Trakt…</div>';try{const response=await fetch(`/api/trakt/search?q=${encodeURIComponent(query)}&sort=popular`);const data=await response.json();if(requestId!==traktSearchRequest)return;if(!response.ok)throw new Error(data.error);const items=data.results||[];target.innerHTML=items.length?items.map(item=>`<button class="search-match" type="button" data-trakt-id="${escapeHTML(item.ids?.trakt)}" data-trakt-type="${escapeHTML(item.mediaType)}">${item.image?`<img src="${escapeHTML(item.image)}" alt="">`:''}<span><b>${escapeHTML(item.title)}</b><small>${escapeHTML([item.mediaType,item.year,item.rating&&`★ ${Number(item.rating).toFixed(1)}`,item.votes&&`${Number(item.votes).toLocaleString()} votes`].filter(Boolean).join(' · '))}</small></span></button>`).join(''):'<div class="search-match-state">No Trakt matches found.</div>'}catch(error){if(requestId===traktSearchRequest)target.innerHTML=`<div class="search-match-state">${escapeHTML(error.message)}</div>`}}
$('#trakt-search-results').addEventListener('click',event=>{const match=event.target.closest('[data-trakt-id]');if(!match)return;$('#trakt-search-results').hidden=true;openTraktDetails(match.dataset.traktType,match.dataset.traktId)});
document.addEventListener('click',event=>{if(!event.target.closest('#search-form'))$('#trakt-search-results').hidden=true});

$('#discover-nav').addEventListener('click',()=>setView('discover'));
$('#library-nav').addEventListener('click',()=>setView('library'));
$('#settings-nav').addEventListener('click',()=>setView('settings'));
$('#library-filter').addEventListener('input',()=>{clearTimeout(librarySearchTimer);librarySearchTimer=setTimeout(()=>{libraryVisibleLimit=250;libraryAutoMatchBudget=12;librarySignature='';refreshLibrary()},250)});
$('#library-sort').addEventListener('change',()=>{librarySignature='';refreshLibrary()});
$('#library-tools').addEventListener('click',event=>{const button=event.target.closest('[data-library-filter]');if(!button)return;librarySourceFilter=button.dataset.libraryFilter;libraryVisibleLimit=250;libraryAutoMatchBudget=12;document.querySelectorAll('[data-library-filter]').forEach(item=>item.classList.toggle('active',item===button));librarySignature='';refreshLibrary()});
async function setView(view){
  currentView=view;clearTimeout(libraryTimer);
  const library=view==='library',settings=view==='settings',discover=view==='discover';
  $('#discover-nav').classList.toggle('active',discover);$('#library-nav').classList.toggle('active',library);$('#settings-nav').classList.toggle('active',settings);
  $('#search-form').hidden=!discover;$('#trakt-dashboard').hidden=!discover;$('#library-tools').hidden=!library;$('#settings-panel').hidden=!settings;results.hidden=settings;results.classList.toggle('library-poster-grid',library);
  if(discover){$('#results-bar').hidden=true;results.innerHTML='';return}
  if(settings){$('#results-bar').hidden=true;await loadTraktSettings();return}
  $('#results-bar').hidden=false;librarySignature='';$('#results-title').textContent='Loading library…';results.innerHTML='<div class="empty"><p>Reading the local library…</p></div>';await refreshLibrary();autoMatchLibrary();
}

async function loadTraktSettings(){
  try{const [traktResponse,torrentResponse,aiResponse]=await Promise.all([fetch('/api/trakt/settings',{cache:'no-store'}),fetch('/api/torrentclaw/settings',{cache:'no-store'}),fetch('/api/ai/settings',{cache:'no-store'})]);const data=await traktResponse.json(),torrent=await torrentResponse.json(),ai=await aiResponse.json();if(!traktResponse.ok)throw new Error(data.error);if(!torrentResponse.ok)throw new Error(torrent.error);if(!aiResponse.ok)throw new Error(ai.error);renderTraktSettings(data);renderTorrentClawSettings(torrent);renderAISettings(ai);}
  catch(error){$('#trakt-account-status').textContent=error.message;}
}
function renderTorrentClawSettings(data){$('#torrentclaw-api-key').value='';$('#torbox-api-key').value='';$('#torrentclaw-api-key').placeholder=data.hasApiKey?'Saved — leave blank to keep':'Required for Play';$('#torbox-api-key').placeholder=data.hasTorBoxKey?'Saved — leave blank to keep':'Optional hosted debrid';$('#torrentclaw-status').textContent=data.configured?`TorrentClaw enabled. ${data.hasTorBoxKey?'TorBox library, search, and instant cache enabled.':'Add TorBox for instant hosted streams.'}`:'Add a free TorrentClaw API key to enable Play.'}
function renderAISettings(data){aiConfigured=Boolean(data.configured);$('#openai-api-key').value='';$('#openai-api-key').placeholder=data.hasApiKey?'Saved — leave blank to keep':'Optional · API billing is separate';$('#openai-model').value=data.model||'gpt-5.6-luna';$('#ai-status').textContent=data.configured?`AI review enabled with ${data.model}. Calls happen only when requested.`:'Deterministic matching is active. Add an API key for AI review.'}
function renderTraktSettings(data){
  $('#trakt-client-id').value=data.clientId||'';
  $('#trakt-client-secret').placeholder=data.hasClientSecret?'Saved — leave blank to keep it':'Enter client secret';
  const label=data.user?.name||data.user?.username;
  $('#trakt-account-title').textContent=data.authenticated?(label||'Connected to Trakt'):'Not connected';
  $('#trakt-account-status').textContent=data.authenticated?'Your personal shelves are enabled.':data.configured?'Credentials saved. Connect your Trakt account next.':'Save application credentials to begin.';
  $('#trakt-connect').disabled=!data.configured||data.authenticated;$('#trakt-connect').hidden=data.authenticated;$('#trakt-disconnect').hidden=!data.authenticated;
}
$('#trakt-settings-form').addEventListener('submit',async event=>{event.preventDefault();const button=event.currentTarget.querySelector('button');button.disabled=true;try{const response=await fetch('/api/trakt/settings',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({clientId:$('#trakt-client-id').value,clientSecret:$('#trakt-client-secret').value})});const data=await response.json();if(!response.ok)throw new Error(data.error);$('#trakt-client-secret').value='';renderTraktSettings(data);toast('Trakt credentials saved');await loadTraktDashboard();}catch(error){alert(`Could not save Trakt settings:\n\n${error.message}`)}finally{button.disabled=false}});
$('#torrentclaw-settings-form').addEventListener('submit',async event=>{event.preventDefault();const button=event.currentTarget.querySelector('button');button.disabled=true;try{const data=await postJSON('/api/torrentclaw/settings',{apiKey:$('#torrentclaw-api-key').value,torboxApiKey:$('#torbox-api-key').value});renderTorrentClawSettings(data);toast('Playback service settings saved')}catch(error){alert(`Could not save playback settings:\n\n${error.message}`)}finally{button.disabled=false}});
$('#ai-settings-form').addEventListener('submit',async event=>{event.preventDefault();const button=event.currentTarget.querySelector('button');button.disabled=true;try{const data=await postJSON('/api/ai/settings',{apiKey:$('#openai-api-key').value,model:$('#openai-model').value});renderAISettings(data);toast('AI matching settings saved')}catch(error){alert(`Could not save AI settings:\n\n${error.message}`)}finally{button.disabled=false}});
$('#export-matches').addEventListener('click',async()=>{try{const response=await fetch('/api/library/matches/export',{cache:'no-store'}),data=await response.json();if(!response.ok)throw new Error(data.error);const link=document.createElement('a');link.href=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'}));link.download='unarr-unmatched-library.json';link.click();setTimeout(()=>URL.revokeObjectURL(link.href),1000);toast(`Exported ${data.items?.length||0} unmatched files`)}catch(error){alert(`Could not export matches:\n\n${error.message}`)}});
$('#import-matches').addEventListener('click',()=>$('#match-import-file').click());
$('#match-import-file').addEventListener('change',async event=>{const file=event.target.files[0];if(!file)return;try{const data=await postJSON('/api/library/matches/import',JSON.parse(await file.text()));toast(`Imported ${data.imported} library mappings`);librarySignature='';if(currentView==='library')refreshLibrary()}catch(error){alert(`Could not import mappings:\n\n${error.message}`)}finally{event.target.value=''}});
$('#trakt-connect').addEventListener('click',async()=>{const button=$('#trakt-connect');button.disabled=true;const authWindow=window.open('about:blank','trakt-auth');try{const response=await fetch('/api/trakt/auth',{method:'POST',headers:{'Content-Type':'application/json'},body:'{}'});const data=await response.json();if(!response.ok)throw new Error(data.error);showTraktDevice(data);if(authWindow)authWindow.location=data.verificationUrl;pollTraktAuth();}catch(error){if(authWindow)authWindow.close();alert(`Could not start Trakt authorization:\n\n${error.message}`);$('#trakt-account-status').textContent=error.message;button.disabled=false}});
function showTraktDevice(data){$('#trakt-device').hidden=false;$('#trakt-code').textContent=data.userCode;$('#trakt-activate').href=data.verificationUrl;$('#trakt-account-status').textContent='Waiting for authorization in your browser…';}
async function pollTraktAuth(){clearTimeout(traktAuthTimer);try{const response=await fetch('/api/trakt/auth',{cache:'no-store'});const data=await response.json();if(data.status==='complete'){$('#trakt-device').hidden=true;toast('Trakt connected');await loadTraktSettings();await loadTraktDashboard();return}if(data.status==='error')throw new Error(data.error);traktAuthTimer=setTimeout(pollTraktAuth,2000)}catch(error){$('#trakt-account-status').textContent=error.message;$('#trakt-connect').disabled=false;}}
$('#trakt-disconnect').addEventListener('click',async()=>{if(!confirm('Disconnect this Trakt account?'))return;const response=await fetch('/api/trakt/auth',{method:'DELETE'});const data=await response.json();if(!response.ok){alert(data.error);return}$('#trakt-device').hidden=true;await loadTraktSettings();await loadTraktDashboard();toast('Trakt disconnected');});
$('#restore-settings').addEventListener('click',()=>$('#restore-file').click());
$('#restore-file').addEventListener('change',async event=>{const file=event.target.files[0];if(!file)return;if(!confirm('Restore this backup and replace the currently connected Trakt settings?')){event.target.value='';return}try{const backup=JSON.parse(await file.text());const response=await fetch('/api/settings/restore',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(backup)});const data=await response.json();if(!response.ok)throw new Error(data.error);renderTraktSettings(data);await loadTraktDashboard();toast('Settings restored')}catch(error){alert(`Could not restore settings:\n\n${error.message}`)}finally{event.target.value=''}});
async function refreshLibrary(){if(currentView!=='library')return;clearTimeout(libraryTimer);try{const query=$('#library-filter').value.trim(),sort=$('#library-sort').value;const response=await fetch(`/api/library?source=${encodeURIComponent(librarySourceFilter)}&q=${encodeURIComponent(query)}&sort=${encodeURIComponent(sort)}&limit=${encodeURIComponent(libraryVisibleLimit)}`,{cache:'no-store'});const data=await response.json();if(!response.ok)throw new Error(data.error);const nextItems=data.items||[];const nextSignature=JSON.stringify(nextItems);const nextTotal=Number(data.total)||0;const changed=nextSignature!==librarySignature||nextTotal!==libraryTotal;libraryItems=nextItems;libraryTotal=nextTotal;librarySignature=nextSignature;if(changed){renderLibrary();if(libraryTotal>libraryItems.length)$('#results-title').textContent=`${libraryTotal} total · showing ${libraryItems.length} matching items`;setTimeout(autoMatchLibrary,0)}}catch(error){results.innerHTML=`<div class="empty"><p>${escapeHTML(error.message)}</p></div>`;}finally{if(currentView==='library')libraryTimer=setTimeout(refreshLibrary,librarySourceFilter==='local'?3000:30000);}}
function renderLibrary(){const term=$('#library-filter').value.trim().toLowerCase();const items=libraryItems.filter(item=>!term||String(item.title||'').toLowerCase().includes(term));$('#results-title').textContent=`${items.length} ${librarySourceFilter==='all'?'library':librarySourceFilter} item${items.length===1?'':'s'}`;if(!items.length){results.innerHTML='<div class="empty"><p>No matching titles in this library.</p></div>';return}results.innerHTML=items.map(item=>{const info=item.mediaInfo||{},video=info.video||{},audio=info.audio||[],subtitles=info.subtitles||[],duration=video.duration?`${Math.floor(video.duration/3600)}h ${Math.round(video.duration%3600/60)}m`:'';const audioOptions=audio.map((track,index)=>`<option value="${index}" ${track.default?'selected':''}>${escapeHTML(trackLabel(track,index,'Audio'))}</option>`).join(''),subtitleOptions=subtitles.map((track,index)=>`<option value="${index}">${escapeHTML(trackLabel(track,index,'Subtitle'))}</option>`).join('');const source=item.source||'local';return `<article class="card library-card" data-item-id="${escapeHTML(item.id)}" data-source="${source}">${item.image?`<img class="library-card-poster" src="${escapeHTML(item.image)}" alt="" draggable="false">`:''}<span class="source-chip">${escapeHTML(source==='favorites'?'Trakt favorite':source)}</span><h3>${escapeHTML(item.title)}</h3><p>${escapeHTML(item.fileName||'')}</p><div class="media-summary">${video.codec?`<span>${escapeHTML(video.codec)}</span>`:''}${duration?`<span>${duration}</span>`:''}${item.fileSize?`<span>${formatBytes(item.fileSize)}</span>`:''}${source==='cloud'&&!item.linked?'<span>Unmatched</span>':''}</div>${source==='local'&&(audio.length||subtitles.length)?`<div class="track-pickers">${audio.length?`<label>Audio<select class="library-audio">${audioOptions}</select></label>`:''}${subtitles.length?`<label>Subtitles<select class="library-subtitle"><option value="-1">Off</option>${subtitleOptions}</select></label>`:''}</div>`:''}${source==='local'?`<button class="play-library" data-library="${item.id}" data-title="${escapeHTML(item.title)}">Play</button>`:source==='cloud'?`<button class="play-cloud" data-cloud-play="${escapeHTML(item.infoHash)}" data-torrent-id="${escapeHTML(item.torrentId)}" data-file-id="${escapeHTML(item.fileId)}" data-file-name="${escapeHTML(item.fileName)}" data-title="${escapeHTML(item.title)}">Play from TorBox</button>`:`<button class="favorite-download" data-title-id="${escapeHTML(item.ids?.trakt||'')}" data-title-type="${escapeHTML(item.mediaType)}">Download options</button>`}</article>`}).join('');}

function cleanMediaTitle(value){return String(value||'').replace(/\.[a-z0-9]{2,5}$/i,'').replace(/[._]+/g,' ').replace(/^\s*(?:\[[^\]]+\]\s*)+/,'').replace(/\s+(?:Season\s*\d+|S\d{1,3}E\d{1,4}|\d{1,2}x\d{1,4}).*$/i,'').replace(/\s+(?:19\d{2}|20\d{2}|2160p|1080p|720p|480p|WEB.?DL|BluRay|BDRip|DVDRip).*$/i,'').replace(/\s+/g,' ').trim()}
function isGenericExtra(value){return /(?:^|\b)(?:extras?|deleted scenes?|alternate (?:takes?|scenes?)|behind the scenes|featurettes?|cast interviews?|interviews?|trailers?|samples?|bloopers?|digital originals?|making of|bonus features?)(?:\b|$)/i.test(cleanMediaTitle(value))}
function groupedLibraryTitle(item){const linked=item.trakt?.title;if(linked)return linked;const folder=cleanMediaTitle(item.folderTitle),file=cleanMediaTitle(item.title||item.fileName);return folder&&!/^(season|downloads?|movies?|shows?|tv)$/i.test(folder)?folder:file||item.title||'Untitled'}
function matchScore(query,item,type){if(item.mediaType!==type)return 0;const words=value=>new Set(String(value).toLowerCase().replace(/[^a-z0-9]+/g,' ').trim().split(/\s+/).filter(Boolean)),a=words(query),b=words(item.title);if(!a.size||!b.size)return 0;const common=[...a].filter(word=>b.has(word)).length,dice=2*common/(a.size+b.size),exact=[...a].join('')===[...b].join('');return exact?1:Math.min(.89,dice+(item.year&&query.includes(String(item.year))?0.08:0))}
async function rankedTraktMatches(group,customQuery){const queries=[customQuery,...group.items.flatMap(item=>[cleanMediaTitle(item.folderTitle),cleanMediaTitle(item.fileName)]),group.title].filter((value,index,all)=>value&&all.indexOf(value)===index).slice(0,4),found=new Map();for(const query of queries){const response=await fetch(`/api/trakt/search?q=${encodeURIComponent(query)}&sort=popular`),data=await response.json();if(!response.ok)throw new Error(data.error);for(const item of data.results||[]){const score=matchScore(query,item,group.type),key=`${item.mediaType}:${item.ids?.trakt}`;if(score>(found.get(key)?.confidence||0))found.set(key,{...item,confidence:score,matchedQuery:query})}if([...found.values()].some(item=>item.confidence===1))break}return [...found.values()].filter(item=>item.confidence>=.35).sort((a,b)=>b.confidence-a.confidence||(b.votes||0)-(a.votes||0)).slice(0,8)}
async function chooseLibraryMatch(group,allowAuto=true){let choices=await rankedTraktMatches(group);if(allowAuto&&choices[0]?.confidence>=.96)return choices[0];if(!choices.length){const query=prompt(`No likely Trakt match was found for “${group.title}”.\n\nSearch Trakt:` ,group.title);if(!query)return null;choices=await rankedTraktMatches(group,query)}if(!choices.length)throw new Error('No Trakt matches found.');const menu=choices.map((item,index)=>`${index+1}. ${item.title} (${item.year||'—'}) · ${Math.round(item.confidence*100)}%`).join('\n'),selection=prompt(`Choose the best Trakt match for “${group.title}”:\n\n${menu}\n\nEnter a number, or Cancel to search again:`, '1');if(selection===null){const query=prompt('Search Trakt with another title:',group.title);return query?chooseLibraryMatch({...group,title:query},false):null}return choices[Number(selection)-1]||null}
function reflectLibraryMatch(group,match,detail){const index=libraryGroups.indexOf(group),card=results.querySelector(`[data-library-group="${index}"]`),image=detail.poster||match.image||'';group.traktId=Number(match.ids.trakt);group.title=match.title;group.image=image;group.released=String(detail.released||detail.year||'');for(const item of group.items)Object.assign(item,{linked:true,title:match.title,image,released:group.released,trakt:{type:match.mediaType,traktId:group.traktId,title:match.title,image,released:group.released}});if(!card)return;if(image){let poster=card.querySelector(':scope > img');if(!poster){poster=document.createElement('img');poster.alt='';poster.draggable=false;poster.loading='lazy';card.prepend(poster)}poster.src=image}card.querySelector('.trakt-card-copy b').textContent=match.title;card.querySelector('.trakt-card-copy small').textContent=[group.released,group.items.length>1&&`${group.items.length} ${group.type==='show'?'episodes/files':'files'}`].filter(Boolean).join(' · ');card.classList.add('matched-live')}
async function autoMatchLibrary(){if(libraryAutoMatching||currentView!=='library'||libraryAutoMatchBudget<1)return;libraryAutoMatching=true;let matched=0;try{for(const group of libraryGroups.filter(item=>!item.traktId&&!isGenericExtra(item.title)).slice(0,Math.min(6,libraryAutoMatchBudget))){libraryAutoMatchBudget--;const match=(await rankedTraktMatches(group))[0];if(!match||match.confidence<.96)continue;const detail=await fetchTraktDetails(match.mediaType,String(match.ids.trakt));for(const item of group.items)await postJSON('/api/library/action',{action:'link',itemId:item.id,type:match.mediaType,traktId:Number(match.ids.trakt),title:match.title,image:detail.poster||match.image||'',released:detail.released||detail.year||''});reflectLibraryMatch(group,match,detail);matched++;$('#results-title').textContent=`Auto-matched ${matched} title${matched===1?'':'s'} · updating live…`}}catch(error){console.warn('Library auto-match paused:',error)}finally{libraryAutoMatching=false;if(matched){if(libraryItems.length<libraryTotal)libraryVisibleLimit=Math.min(5000,libraryTotal,libraryVisibleLimit+250);libraryAutoMatchBudget=12;librarySignature='';refreshLibrary()}}}
function renderLibrary(){const groups=new Map();for(const item of libraryItems){const identity=item.trakt?.traktId||item.ids?.trakt,type=item.trakt?.type||item.mediaType||(item.season||/S\d+E\d+/i.test(item.fileName||'')?'show':'movie'),title=groupedLibraryTitle(item),key=identity?`${type}:${identity}`:`${type}:${title.toLowerCase()}`;if(!groups.has(key))groups.set(key,{key,type,traktId:identity,title,items:[],image:null,dateAdded:'',released:'',source:item.source});const group=groups.get(key);group.items.push(item);if(item.image&&!group.image)group.image=item.image;if(item.dateAdded>group.dateAdded)group.dateAdded=item.dateAdded;if(String(item.released||item.year||'')>group.released)group.released=String(item.released||item.year||'');if(item.source==='favorites')group.source='favorites'}libraryGroups=[...groups.values()];const sort=$('#library-sort').value;libraryGroups.sort((a,b)=>sort==='za'?b.title.localeCompare(a.title):sort==='added'?String(b.dateAdded).localeCompare(String(a.dateAdded)):sort==='released'?String(b.released).localeCompare(String(a.released)):a.title.localeCompare(b.title));$('#results-title').textContent=`${libraryGroups.length} grouped title${libraryGroups.length===1?'':'s'}${libraryTotal>libraryItems.length?` · first ${libraryItems.length} files`:''}`;if(!libraryGroups.length){results.innerHTML='<div class="empty"><p>No matching titles in this library.</p></div>';return}results.innerHTML=libraryGroups.map((group,index)=>{const item=group.items[0],count=group.items.length>1?`${group.items.length} ${group.type==='show'?'episodes/files':'files'}`:'';return `<button class="library-poster library-card" data-library-group="${index}" data-item-id="${escapeHTML(item.id)}" data-source="${escapeHTML(item.source)}" aria-label="Open ${escapeHTML(group.title)}">${group.image?`<img src="${escapeHTML(group.image)}" alt="" draggable="false" loading="lazy">`:''}<span class="trakt-shade"></span><span class="source-chip">${escapeHTML(group.source==='favorites'?'Trakt favorite':group.source)}</span><span class="trakt-card-copy"><b>${escapeHTML(group.title)}</b><small>${escapeHTML([group.released,count,!group.traktId&&'Hold to match'].filter(Boolean).join(' · '))}</small></span></button>`}).join('')}
results.addEventListener('click',event=>{const card=event.target.closest('[data-library-group]');if(!card)return;const group=libraryGroups[Number(card.dataset.libraryGroup)];if(suppressLibraryClick){suppressLibraryClick=false;return}openLibraryGroup(group,card)});
async function openLibraryGroup(group,card){if(group?.traktId){openTraktDetails(group.type,String(group.traktId));return}try{const match=await chooseLibraryMatch(group);if(!match){openLibraryActions(card);return}const detail=await fetchTraktDetails(match.mediaType,String(match.ids.trakt));for(const item of group.items)await postJSON('/api/library/action',{action:'link',itemId:item.id,type:match.mediaType,traktId:Number(match.ids.trakt),title:match.title,image:detail.poster||match.image||'',released:detail.released||detail.year||''});group.traktId=Number(match.ids.trakt);group.image=detail.poster||match.image;openTraktDetails(match.mediaType,String(match.ids.trakt));librarySignature=''}catch(error){openLibraryActions(card);toast(`Use Match with Trakt: ${error.message}`)}}

function render(items){ $('#results-title').textContent=`${items.length} result${items.length===1?'':'s'}`; if(!items.length){results.innerHTML='<div class="empty"><p>No matches found. Try a broader search.</p></div>';return}
  results.innerHTML=items.map(item=>{const torrents=item.torrents||item.releases||[]; const title=item.title||item.name||'Untitled'; const rating=item.ratingImdb||item.ratingTmdb||item.rating; return `<article class="card"><div class="meta">${escapeHTML([item.contentType||item.type,item.year,rating&&`★ ${rating}`].filter(Boolean).join(' · '))}</div><h3>${escapeHTML(title)}</h3><p>${escapeHTML(item.overview||item.description||'')}</p><div class="releases">${torrents.slice(0,3).map(release=>{const hash=release.infoHash||release.info_hash||'';return `<div class="release"><b>${escapeHTML(release.quality||release.resolution||'Release')}</b><span>${escapeHTML(String(release.seeders??''))}${release.seeders!=null?' seeds':''}</span>${hash?`<button data-download="${escapeHTML(hash)}">Download</button><button class="stream" data-stream="${escapeHTML(hash)}" data-title="${escapeHTML(title)}">Stream</button>`:''}</div>`}).join('')}</div></article>`}).join('');
}
results.addEventListener('click',async event=>{const button=event.target.closest('[data-download]');if(!button)return;button.disabled=true;button.textContent='Starting…';try{const response=await fetch('/api/download',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({infoHash:button.dataset.download})});const data=await response.json();if(!response.ok)throw new Error(data.error);button.textContent='Started';toast('Download started in unarr');}catch(error){button.disabled=false;button.textContent='Download';toast(error.message)}});
results.addEventListener('click',async event=>{const button=event.target.closest('[data-stream]');if(!button)return;button.disabled=true;alert('Unarr will find peers and build a playback buffer. The web player will open now and show live progress.');await launchPlayer('/api/stream',{infoHash:button.dataset.stream},button.dataset.title,button);});
results.addEventListener('click',async event=>{const button=event.target.closest('[data-library]');if(!button)return;button.disabled=true;const card=button.closest('.library-card');const audioIndex=Number(card.querySelector('.library-audio')?.value||0);const subtitleIndex=Number(card.querySelector('.library-subtitle')?.value??-1);alert('Unarr will prepare browser-compatible HLS. The web player will open now.');await launchPlayer('/api/library/stream',{itemId:button.dataset.library,quality:'original',audioIndex,subtitleIndex},button.dataset.title,button);});
results.addEventListener('click',async event=>{const button=event.target.closest('[data-cloud-play]');if(!button)return;button.disabled=true;try{const response=await postJSON('/api/torrentclaw/debrid/play',{infoHash:button.dataset.cloudPlay,torrentId:Number(button.dataset.torrentId),fileId:Number(button.dataset.fileId),fileName:button.dataset.fileName});currentReleaseTitle=button.dataset.title;currentReleaseMedia=null;location.href=playerPath(response.id)}catch(error){button.disabled=false;alert(`Playback could not start:\n\n${error.message}`)}});
results.addEventListener('click',event=>{const button=event.target.closest('.favorite-download');if(button)openTraktDetails(button.dataset.titleType,button.dataset.titleId)});
function openLibraryActions(card){libraryActionItem=libraryItems.find(item=>item.id===card.dataset.itemId);libraryActionGroup=card.dataset.libraryGroup!=null?libraryGroups[Number(card.dataset.libraryGroup)]:null;if(!libraryActionItem)return;$('#library-action-title').textContent=libraryActionGroup?.title||libraryActionItem.title;const source=libraryActionItem.source;const actions=[];if(aiConfigured&&libraryActionGroup&&!libraryActionGroup.traktId)actions.push(['ai-review','Review with AI']);if(source==='cloud'&&!libraryActionItem.linked)actions.push(['match','Match with Trakt']);if(source==='favorites')actions.push(['unfavorite','Unfavorite']);if(source==='cloud')actions.push(['download-local','Download to local']);if(source!=='favorites')actions.push(['delete',source==='cloud'?'Delete from TorBox':'Delete local file']);$('#library-action-buttons').innerHTML=actions.map(([action,label])=>`<button data-library-action="${action}">${label}</button>`).join('');$('#library-actions').showModal()}
async function applyLibraryMatch(group,match){const detail=await fetchTraktDetails(match.mediaType,String(match.ids.trakt));for(const item of group.items)await postJSON('/api/library/action',{action:'link',itemId:item.id,type:match.mediaType,traktId:Number(match.ids.trakt),title:match.title,image:detail.poster||match.image||'',released:detail.released||detail.year||''});group.traktId=Number(match.ids.trakt);group.image=detail.poster||match.image;librarySignature='';return detail}
async function reviewLibraryGroupWithAI(group){const candidates=await rankedTraktMatches(group),response=await postJSON('/api/library/ai-match',{title:group.title,type:group.type,files:group.items.map(item=>({fileName:item.fileName,folderTitle:item.folderTitle})),candidates:candidates.map(item=>({traktId:Number(item.ids.trakt),title:item.title,year:item.year,type:item.mediaType,score:item.confidence}))}),decision=response.decision||{};if(decision.classification==='extra')throw new Error(`AI classified this as an extra: ${decision.reason}`);const match=candidates.find(item=>Number(item.ids.trakt)===Number(decision.traktId));if(!match)throw new Error(`AI could not select a confident Trakt match: ${decision.reason||'uncertain'}`);if(!confirm(`AI suggests “${match.title}” (${Math.round(Number(decision.confidence||0)*100)}%).\n\n${decision.reason}\n\nApply this match?`))return;await applyLibraryMatch(group,match);$('#library-actions').close();toast(`AI matched ${match.title}`);refreshLibrary()}
$('#library-action-buttons').addEventListener('click',event=>{const button=event.target.closest('[data-library-action="ai-review"]');if(!button)return;event.stopImmediatePropagation();button.disabled=true;reviewLibraryGroupWithAI(libraryActionGroup).catch(error=>alert(`AI review failed:\n\n${error.message}`)).finally(()=>button.disabled=false)},true);
results.addEventListener('pointerdown',event=>{const card=event.target.closest('.library-card');if(!card||event.target.closest('button,select'))return;clearTimeout(libraryHoldTimer);libraryHoldTimer=setTimeout(()=>{suppressLibraryClick=true;navigator.vibrate?.(30);openLibraryActions(card)},550)});
for(const name of ['pointerup','pointercancel','pointerleave'])results.addEventListener(name,()=>clearTimeout(libraryHoldTimer));
results.addEventListener('pointermove',event=>{if(Math.abs(event.movementX)>3||Math.abs(event.movementY)>3)clearTimeout(libraryHoldTimer)});
results.addEventListener('contextmenu',event=>{const card=event.target.closest('.library-card');if(!card)return;event.preventDefault();openLibraryActions(card)});
$('#close-library-actions').addEventListener('click',()=>$('#library-actions').close());
$('#library-action-buttons').addEventListener('click',async event=>{const button=event.target.closest('[data-library-action]');if(!button||!libraryActionItem)return;const action=button.dataset.libraryAction;button.disabled=true;try{if(action==='match'){const query=prompt('Search Trakt for this cloud file:',libraryActionItem.title);if(!query)return;const data=await (await fetch(`/api/trakt/search?q=${encodeURIComponent(query)}&sort=popular`)).json();const choices=(data.results||[]).slice(0,8);if(!choices.length)throw new Error('No Trakt matches found.');const selection=prompt(choices.map((item,index)=>`${index+1}. ${item.title} (${item.year||'—'}) · ${item.mediaType}`).join('\n')+'\n\nEnter a number:','1');const match=choices[Number(selection)-1];if(!match)return;await postJSON('/api/library/action',{action:'link',itemId:libraryActionItem.id,type:match.mediaType,traktId:Number(match.ids.trakt),title:match.title,image:match.image||''});toast('Cloud file matched with Trakt')}else if(action==='download-local'){const response=await postJSON('/api/library/action',{action,itemId:libraryActionItem.id});await postJSON('/api/download',{infoHash:response.infoHash});toast('Local download started');await refreshActivity(true)}else{if(action==='delete'&&!confirm(`Permanently delete “${libraryActionItem.title}”?`))return;await postJSON('/api/library/action',{action,itemId:libraryActionItem.id});toast(action==='unfavorite'?'Removed from Trakt favorites':'Deleted')}$('#library-actions').close();librarySignature='';await refreshLibrary()}catch(error){alert(`Library action failed:\n\n${error.message}`)}finally{button.disabled=false}});
async function launchPlayer(endpoint,body,title,button){try{const response=await fetch(endpoint,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const data=await response.json();if(!response.ok)throw new Error(data.error);location.href=`/watch.html?session=${encodeURIComponent(data.id)}&title=${encodeURIComponent(title)}`;}catch(error){button.disabled=false;alert(`Playback could not start:\n\n${error.message}`);}}
$('#connection').addEventListener('click',async()=>{const dialog=$('#status-dialog');dialog.showModal();$('#status-output').textContent='Loading…';try{const response=await fetch('/api/status');const data=await response.json();if(!response.ok)throw new Error(data.error);$('#status-output').textContent=data.output}catch(error){$('#status-output').textContent=error.message}}); $('#close-dialog').addEventListener('click',()=>$('#status-dialog').close());
async function refreshActivity(open=false){clearTimeout(activityTimer);try{const response=await fetch('/api/activity',{cache:'no-store'}),data=await response.json();const items=data.items||[],active=items.filter(item=>item.status==='active').length;$('#activity-count').hidden=!active;$('#activity-count').textContent=active;$('#activity-results').innerHTML=items.length?items.map(item=>`<article class="activity-item ${escapeHTML(item.status)}"><span>${item.status==='complete'?'✓':item.status==='error'?'!':'↻'}</span><div><strong>${escapeHTML(item.provider==='torbox'?'TorBox':'Local Unarr')}</strong><p>${escapeHTML(item.message)}</p><small>${escapeHTML(item.infoHash.slice(0,8))}</small></div></article>`).join(''):'<div class="detail-loading">No download activity yet.</div>';if(open&&!$('#activity-dialog').open)$('#activity-dialog').showModal()}catch(error){}finally{activityTimer=setTimeout(refreshActivity,3000)}}
$('#activity-button').addEventListener('click',()=>refreshActivity(true));$('#close-activity-dialog').addEventListener('click',()=>$('#activity-dialog').close());refreshActivity();
function escapeHTML(value){return String(value??'').replace(/[&<>'"]/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[char]))}
function formatBytes(value){const units=['B','KB','MB','GB','TB'];let size=Number(value)||0,index=0;while(size>=1000&&index<units.length-1){size/=1000;index++}return `${size.toFixed(index?1:0)} ${units[index]}`}
function trackLabel(track,index,prefix){const imageSubtitles=['hdmv_pgs_subtitle','dvd_subtitle','dvb_subtitle'];const parts=[track.lang&&track.lang.toUpperCase(),track.title,track.codec,imageSubtitles.includes(track.codec)&&'burn-in',track.channels&&`${track.channels}ch`].filter(Boolean);return parts.join(' · ')||`${prefix} ${index+1}`}
function formatCalendarDate(value){const date=new Date(value);return Number.isNaN(date.getTime())?'':date.toLocaleDateString(undefined,{month:'short',day:'numeric'})}
