const $ = (selector) => document.querySelector(selector);
const results = $('#results');
let libraryItems=[];
let currentView='discover', libraryTimer=null;
let librarySignature='';
const toast = (message) => { const el=$('#toast'); el.textContent=message; el.classList.add('show'); setTimeout(()=>el.classList.remove('show'),2600); };

fetch('/api/health').then(async response => {
  const data=await response.json(); if(!response.ok) throw new Error(data.error);
  $('#connection').textContent=data.version; $('#connection').classList.add('ok');
}).catch(error => { $('#connection').textContent='CLI unavailable'; $('#connection').title=error.message; });

$('#search-form').addEventListener('submit', async event => {
  event.preventDefault(); const params=new URLSearchParams(new FormData(event.currentTarget));
  $('#results-title').textContent=`Searching for “${params.get('q')}”…`; results.innerHTML='<div class="empty"><p>Searching your catalog…</p></div>';
  try { const response=await fetch(`/api/search?${params}`); const data=await response.json(); if(!response.ok) throw new Error(data.error); render(data.results || []); }
  catch(error){ results.innerHTML=`<div class="empty"><p>${escapeHTML(error.message)}</p></div>`; $('#results-title').textContent='Search unavailable'; }
});

$('#discover-nav').addEventListener('click',()=>setView('discover'));
$('#library-nav').addEventListener('click',()=>setView('library'));
$('#library-filter').addEventListener('input',renderLibrary);
async function setView(view){currentView=view;clearTimeout(libraryTimer);const library=view==='library';$('#discover-nav').classList.toggle('active',!library);$('#library-nav').classList.toggle('active',library);$('#search-form').hidden=library;$('#library-tools').hidden=!library;if(!library){$('#hero-eyebrow').textContent='YOUR LIBRARY, UNCOMPLICATED';$('#hero-title').innerHTML='Find it. Queue it.<br><em>Keep it local.</em>';$('#hero-lede').textContent='A calm interface for the unarr already running on your machine.';$('#results-title').textContent='Ready to discover';results.innerHTML='<div class="empty"><span>⌕</span><p>Search the catalog to begin.</p></div>';return}librarySignature='';$('#hero-eyebrow').textContent='ON THIS MAC · LIVE';$('#hero-title').innerHTML='Your collection.<br><em>Ready to play.</em>';$('#hero-lede').textContent='The files on disk, reconciled live with Unarr metadata.';$('#results-title').textContent='Loading library…';results.innerHTML='<div class="empty"><p>Reading the local library…</p></div>';await refreshLibrary();}
async function refreshLibrary(){if(currentView!=='library')return;try{const response=await fetch('/api/library',{cache:'no-store'});const data=await response.json();if(!response.ok)throw new Error(data.error);const nextItems=data.items||[];const nextSignature=JSON.stringify(nextItems);const changed=nextSignature!==librarySignature;libraryItems=nextItems;librarySignature=nextSignature;const scan=data.scan||{};const scanLabel={scheduled:'Scan scheduled',running:'Scanning metadata…',complete:'Scan complete',error:'Scan failed',idle:'Watching'}[scan.status]||'Watching';$('#transcode-state').textContent=data.transcode.available?`Live · ${scanLabel} · HLS ready`:`${scanLabel} · ffmpeg unavailable`;$('#transcode-state').title=scan.message||'';if(changed)renderLibrary();}catch(error){results.innerHTML=`<div class="empty"><p>${escapeHTML(error.message)}</p></div>`;}finally{if(currentView==='library')libraryTimer=setTimeout(refreshLibrary,3000);}}
function renderLibrary(){const term=$('#library-filter').value.trim().toLowerCase();const items=libraryItems.filter(item=>!term||`${item.title} ${item.fileName} ${item.year}`.toLowerCase().includes(term));$('#results-title').textContent=`${items.length} live library item${items.length===1?'':'s'}`;if(!items.length){results.innerHTML='<div class="empty"><p>No media files are currently present in the configured library paths.</p></div>';return}results.innerHTML=items.map(item=>{const info=item.mediaInfo||{};const video=info.video||{};const audio=info.audio||[];const subtitles=info.subtitles||[];const integrity=info.integrity||{};const duration=video.duration?`${Math.floor(video.duration/3600)}h ${Math.round(video.duration%3600/60)}m`:'';const audioOptions=audio.map((track,index)=>`<option value="${index}" ${track.default?'selected':''}>${escapeHTML(trackLabel(track,index,'Audio'))}</option>`).join('');const subtitleOptions=subtitles.map((track,index)=>`<option value="${index}">${escapeHTML(trackLabel(track,index,'Subtitle'))}</option>`).join('');return `<article class="card library-card"><div class="meta">${escapeHTML([item.year,item.quality,item.season&&`S${item.season}E${item.episode}`,!item.indexed&&'NEW'].filter(Boolean).join(' · '))}</div><h3>${escapeHTML(item.title)}</h3><p>${escapeHTML(item.fileName)}</p>${integrity.damaged?`<p class="integrity">Warning: ${escapeHTML(integrity.reason||'integrity issue')}</p>`:''}<div class="media-summary"><span>${escapeHTML(video.codec||item.codec||'unscanned')}</span>${video.width?`<span>${video.width}×${video.height}</span>`:''}${video.hdr?`<span>${escapeHTML(video.hdr)}</span>`:''}${duration?`<span>${duration}</span>`:''}<span>${formatBytes(item.fileSize)}</span></div>${audio.length||subtitles.length?`<div class="track-pickers">${audio.length?`<label>Audio<select class="library-audio">${audioOptions}</select></label>`:''}${subtitles.length?`<label>Subtitles<select class="library-subtitle"><option value="-1">Off</option>${subtitleOptions}</select></label>`:''}</div>`:''}<button class="play-library" data-library="${item.id}" data-title="${escapeHTML(item.title)}">Play with HLS</button></article>`}).join('');}

function render(items){ $('#results-title').textContent=`${items.length} result${items.length===1?'':'s'}`; if(!items.length){results.innerHTML='<div class="empty"><p>No matches found. Try a broader search.</p></div>';return}
  results.innerHTML=items.map(item=>{const torrents=item.torrents||item.releases||[]; const title=item.title||item.name||'Untitled'; const rating=item.ratingImdb||item.ratingTmdb||item.rating; return `<article class="card"><div class="meta">${escapeHTML([item.contentType||item.type,item.year,rating&&`★ ${rating}`].filter(Boolean).join(' · '))}</div><h3>${escapeHTML(title)}</h3><p>${escapeHTML(item.overview||item.description||'')}</p><div class="releases">${torrents.slice(0,3).map(release=>{const hash=release.infoHash||release.info_hash||'';return `<div class="release"><b>${escapeHTML(release.quality||release.resolution||'Release')}</b><span>${escapeHTML(String(release.seeders??''))}${release.seeders!=null?' seeds':''}</span>${hash?`<button data-download="${escapeHTML(hash)}">Download</button><button class="stream" data-stream="${escapeHTML(hash)}" data-title="${escapeHTML(title)}">Stream</button>`:''}</div>`}).join('')}</div></article>`}).join('');
}
results.addEventListener('click',async event=>{const button=event.target.closest('[data-download]');if(!button)return;button.disabled=true;button.textContent='Starting…';try{const response=await fetch('/api/download',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({infoHash:button.dataset.download})});const data=await response.json();if(!response.ok)throw new Error(data.error);button.textContent='Started';toast('Download started in unarr');}catch(error){button.disabled=false;button.textContent='Download';toast(error.message)}});
let streamSession=null, streamPoll=null;
results.addEventListener('click',async event=>{const button=event.target.closest('[data-stream]');if(!button)return;button.disabled=true;const dialog=$('#player-dialog');$('#player-title').textContent=button.dataset.title;renderStreamProgress({phase:'metadata',message:'Starting unarr…',elapsedSeconds:0,metadataTimeoutSeconds:60});dialog.showModal();try{const response=await fetch('/api/stream',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({infoHash:button.dataset.stream})});const data=await response.json();if(!response.ok)throw new Error(data.error);streamSession=data.id;pollStream();}catch(error){renderStreamError(error.message);button.disabled=false;}});
results.addEventListener('click',async event=>{const button=event.target.closest('[data-library]');if(!button)return;button.disabled=true;const card=button.closest('.library-card');const audioIndex=Number(card.querySelector('.library-audio')?.value||0);const subtitleIndex=Number(card.querySelector('.library-subtitle')?.value??-1);const dialog=$('#player-dialog');$('#player-title').textContent=button.dataset.title;renderStreamProgress({phase:'transcoding',message:'Starting HLS transcode…',elapsedSeconds:0});dialog.showModal();try{const response=await fetch('/api/library/stream',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({itemId:button.dataset.library,quality:$('#library-quality').value,audioIndex,subtitleIndex})});const data=await response.json();if(!response.ok)throw new Error(data.error);streamSession=data.id;pollStream();}catch(error){renderStreamError(error.message);button.disabled=false;}});
async function pollStream(){clearTimeout(streamPoll);if(!streamSession)return;try{const response=await fetch(`/api/stream/${encodeURIComponent(streamSession)}`);const data=await response.json();if(!response.ok)throw new Error(data.error);if(data.status==='ready'&&data.url){const tracks=(data.tracks||[]).map(track=>`<track kind="${escapeHTML(track.kind)}" src="${escapeHTML(track.src)}" srclang="${escapeHTML(track.srclang)}" label="${escapeHTML(track.label)}" ${track.default?'default':''}>`).join('');$('#player-stage').innerHTML=`<video controls autoplay playsinline src="${escapeHTML(data.url)}">${tracks}</video>`;return}if(data.status==='error')throw new Error(data.error||'Stream failed.');if(data.status==='stopped')throw new Error('Stream stopped before playback became ready.');renderStreamProgress(data);streamPoll=setTimeout(pollStream,1000);}catch(error){renderStreamError(error.message);}};
function renderStreamProgress(data){const metadata=data.phase==='metadata';const elapsed=data.elapsedSeconds||0;const timeout=data.metadataTimeoutSeconds||60;const percent=metadata?Math.min(100,Math.round(elapsed/timeout*100)):(data.progress||0);const detail=metadata?`Metadata deadline: ${elapsed}s of ${timeout}s`:data.message;$('#player-stage').innerHTML=`<div class="stream-progress"><div class="spinner"></div><strong>${escapeHTML(data.message||'Preparing stream…')}</strong><span>${escapeHTML(detail)}</span><div class="progress-track"><i style="width:${percent}%"></i></div>${metadata?'<small>If no peers provide metadata within 60 seconds, unarr will stop this attempt.</small>':''}</div>`;}
function renderStreamError(message){$('#player-stage').innerHTML=`<div class="stream-error"><strong>Couldn’t start playback</strong><span>${escapeHTML(message)}</span><small>Try a release with more seeders or choose another quality.</small></div>`;}
async function closePlayer(){clearTimeout(streamPoll);const id=streamSession;streamSession=null;$('#player-dialog').close();$('#player-stage').innerHTML='';document.querySelectorAll('[data-stream]:disabled,[data-library]:disabled').forEach(button=>button.disabled=false);if(id)await fetch(`/api/stream/${encodeURIComponent(id)}`,{method:'DELETE'}).catch(()=>{});} $('#close-player').addEventListener('click',closePlayer); $('#player-dialog').addEventListener('cancel',event=>{event.preventDefault();closePlayer()});
$('#status-button').addEventListener('click',async()=>{const dialog=$('#status-dialog');dialog.showModal();$('#status-output').textContent='Loading…';try{const response=await fetch('/api/status');const data=await response.json();if(!response.ok)throw new Error(data.error);$('#status-output').textContent=data.output}catch(error){$('#status-output').textContent=error.message}}); $('#close-dialog').addEventListener('click',()=>$('#status-dialog').close());
function escapeHTML(value){return String(value??'').replace(/[&<>'"]/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[char]))}
function formatBytes(value){const units=['B','KB','MB','GB','TB'];let size=Number(value)||0,index=0;while(size>=1000&&index<units.length-1){size/=1000;index++}return `${size.toFixed(index?1:0)} ${units[index]}`}
function trackLabel(track,index,prefix){const imageSubtitles=['hdmv_pgs_subtitle','dvd_subtitle','dvb_subtitle'];const parts=[track.lang&&track.lang.toUpperCase(),track.title,track.codec,imageSubtitles.includes(track.codec)&&'burn-in',track.channels&&`${track.channels}ch`].filter(Boolean);return parts.join(' · ')||`${prefix} ${index+1}`}
