const params=new URLSearchParams(location.search);const session=params.get('session'),externalUrl=params.get('url');const title=params.get('title')||'Unarr player';const trakt={type:params.get('traktType'),traktId:Number(params.get('traktId'))||0,season:Number(params.get('season'))||0,episode:Number(params.get('episode'))||0,showTitle:params.get('showTitle')||'',imdbId:params.get('imdbId')||'',tmdbId:params.get('tmdbId')||''};let pollTimer=null,stopped=false,total=0,lastScrobble=0,currentVideo=null,selectedAudio=Number(params.get('audioIndex'))||0,selectedSubtitle=Number(params.get('subtitleIndex')??-1),autoTracks=params.get('autoTracks')==='1';document.querySelector('#title').textContent=title;
if(externalUrl){openVideo({url:externalUrl});}else if(!session){showError('No stream source was provided.')}else{poll();}
async function poll(){try{const response=await fetch(`/api/stream/${encodeURIComponent(session)}`,{cache:'no-store'});const data=await response.json();if(!response.ok)throw new Error(data.error);total=Number(data.durationSeconds)||0;if(data.status==='selecting'){showTrackSelection(data);return}if(data.status==='ready'&&data.url){openVideo(data);return}if(data.status==='error')throw new Error(data.error||'Stream failed.');if(data.status==='stopped')throw new Error('The stream stopped before playback was ready.');showProgress(data);pollTimer=setTimeout(poll,1000);}catch(error){showError(error.message);}}
function showTrackSelection(data){const audio=data.availableAudio||[],subtitles=data.availableSubtitles||[];const options=(items,prefix)=>items.map((track,index)=>`<option value="${index}" ${track.default?'selected':''}>${escapeHTML(trackName(track,index,prefix))}</option>`).join('');document.querySelector('#stage').innerHTML='<div class="preparing"><h1>Ready to play</h1><p>Select playback tracks below.</p></div>';const controls=document.querySelector('#track-controls');controls.hidden=false;controls.innerHTML=`<form id="track-form"><label>Audio<select id="audio-select">${options(audio,'Audio')}</select></label><label>Subtitles<select id="subtitle-select"><option value="-1">Off</option>${options(subtitles,'Subtitle')}</select></label><button>Start playback</button></form>`;document.querySelector('#track-form').addEventListener('submit',startSelectedTracks);if(autoTracks){autoTracks=false;document.querySelector('#audio-select').value=String(Math.min(selectedAudio,Math.max(0,audio.length-1)));document.querySelector('#subtitle-select').value=String(selectedSubtitle>=0&&selectedSubtitle<subtitles.length?selectedSubtitle:-1);document.querySelector('#track-form').requestSubmit()}}
function trackName(track,index,prefix){return [track.lang&&track.lang.toUpperCase(),track.title,track.codec,track.channels&&`${track.channels}ch`].filter(Boolean).join(' · ')||`${prefix} ${index+1}`}
async function startSelectedTracks(event){event.preventDefault();const button=event.currentTarget.querySelector('button');button.disabled=true;selectedAudio=Number(document.querySelector('#audio-select').value||0);selectedSubtitle=Number(document.querySelector('#subtitle-select').value??-1);try{const response=await fetch('/api/stream/tracks',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({sessionId:session,audioIndex:selectedAudio,subtitleIndex:selectedSubtitle})});const data=await response.json();if(!response.ok)throw new Error(data.error);document.querySelector('#track-controls').hidden=true;document.querySelector('#stage').innerHTML='<div class="preparing"><i></i><h1 id="state">Preparing selected tracks…</h1><p id="detail">Starting HLS playback.</p><div class="bar"><span id="bar"></span></div></div>';poll()}catch(error){button.disabled=false;alert(error.message)}}
function showProgress(data){const elapsed=Number(data.elapsedSeconds)||0;const timeout=Number(data.metadataTimeoutSeconds)||60;const metadata=data.phase==='metadata';const percent=metadata?Math.min(100,elapsed/timeout*100):(Number(data.progress)||4);document.querySelector('#state').textContent=data.message||'Preparing stream…';document.querySelector('#detail').textContent=metadata?`Waiting for metadata: ${elapsed}s of ${timeout}s`:phaseLabel(data.phase,elapsed);document.querySelector('#bar').style.width=`${percent}%`;document.querySelector('#runtime').textContent=`00:00 / ${formatTime(total)}`;}
function phaseLabel(phase,elapsed){return {buffering:`Building playback buffer · ${elapsed}s`,transcoding:`Encoding browser-compatible video · ${elapsed}s`,streaming:`Downloading and preparing playback · ${elapsed}s`}[phase]||`Preparing · ${elapsed}s`;}
function openVideo(data){const tracks=(data.tracks||[]).map(track=>`<track kind="${escapeHTML(track.kind)}" src="${escapeHTML(track.src)}" srclang="${escapeHTML(track.srclang)}" label="${escapeHTML(track.label)}" ${track.default?'default':''}>`).join('');document.querySelector('#stage').innerHTML=`<video controls autoplay playsinline src="${escapeHTML(data.url)}">${tracks}</video>`;const video=document.querySelector('video');currentVideo=video;const audio=data.audio;document.querySelector('#track').textContent=audio?[audio.lang?.toUpperCase(),audio.title,audio.codec].filter(Boolean).join(' · '):'HLS player';video.addEventListener('loadedmetadata',()=>{if(!total&&Number.isFinite(video.duration))total=video.duration;updateRuntime(video)});video.addEventListener('play',()=>sendScrobble('start'));video.addEventListener('pause',()=>{if(!video.ended)sendScrobble('pause')});video.addEventListener('ended',autoPlayNext);video.addEventListener('timeupdate',()=>{updateRuntime(video);if(Date.now()-lastScrobble>30000)sendScrobble('start')});}
async function autoPlayNext(){await sendScrobble('stop',100);if(trakt.type!=='show'||!trakt.traktId)return;document.querySelector('#stage').innerHTML='<div class="preparing"><i></i><h1>Finding next episode…</h1><p>Checking cached TorBox sources first.</p></div>';try{let season=trakt.season,episode=trakt.episode+1;let response=await fetch(`/api/trakt/details?type=show&id=${trakt.traktId}&season=${season}`),details=await response.json();if(!(details.episodes||[]).some(item=>item.number===episode)){const show=await (await fetch(`/api/trakt/details?type=show&id=${trakt.traktId}`)).json();const next=(show.seasons||[]).filter(item=>item.number>season).sort((a,b)=>a.number-b.number)[0];if(!next)throw new Error('No next episode is available.');season=next.number;episode=1}const media={type:'show',title:`${trakt.showTitle} S${season}E${episode}`,traktId:trakt.traktId,imdbId:trakt.imdbId||null,tmdbId:trakt.tmdbId||null,season,episode};const releases=await postPlayerJSON('/api/torrentclaw/releases',media);const choices=(releases.groups||[]).flatMap(group=>group.releases||[]);const release=choices.find(item=>item.instant&&item.debridProvider==='TorBox');if(!release)throw new Error('No instant TorBox source was found for the next episode.');const next=await postPlayerJSON('/api/torrentclaw/debrid/play',{infoHash:release.infoHash,torrentId:release.torrentId,fileId:release.fileId,fileName:release.rawTitle||''});const query=new URLSearchParams({session:next.id,title:media.title,traktType:'show',traktId:trakt.traktId,showTitle:trakt.showTitle,imdbId:trakt.imdbId,tmdbId:trakt.tmdbId,season,episode,audioIndex:selectedAudio,subtitleIndex:selectedSubtitle,autoTracks:'1'});location.replace(`/watch.html?${query}`)}catch(error){showError(`Next episode could not start: ${error.message}`)}}
async function postPlayerJSON(path,body){const response=await fetch(path,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const data=await response.json();if(!response.ok)throw new Error(data.error);return data}
function playbackProgress(){if(!currentVideo)return 0;const duration=total||currentVideo.duration;return Number.isFinite(duration)&&duration>0?Math.max(0,Math.min(100,currentVideo.currentTime/duration*100)):0}
async function sendScrobble(action,forcedProgress){if(!trakt.traktId||!['movie','show'].includes(trakt.type))return;lastScrobble=Date.now();const body={action,type:trakt.type,traktId:trakt.traktId,progress:forcedProgress??playbackProgress()};if(trakt.type==='show'){body.season=trakt.season;body.episode=trakt.episode}try{await fetch('/api/trakt/scrobble',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body),keepalive:action==='stop'})}catch(error){}}
function updateRuntime(video){document.querySelector('#runtime').textContent=`${formatTime(video.currentTime)} / ${formatTime(total||video.duration)}`;}
function seekBy(seconds){if(!currentVideo)return;const duration=total||currentVideo.duration;currentVideo.currentTime=Math.max(0,Math.min(Number.isFinite(duration)?duration:currentVideo.currentTime+seconds,currentVideo.currentTime+seconds))}
document.querySelector('#seek-back').addEventListener('click',()=>seekBy(-10));document.querySelector('#seek-forward').addEventListener('click',()=>seekBy(30));document.addEventListener('keydown',event=>{if(['INPUT','SELECT','TEXTAREA'].includes(event.target.tagName))return;if(event.key==='ArrowLeft'){event.preventDefault();seekBy(-10)}if(event.key==='ArrowRight'){event.preventDefault();seekBy(30)}});
function formatTime(seconds){if(!Number.isFinite(seconds)||seconds<=0)return'--:--';const value=Math.round(seconds);const h=Math.floor(value/3600),m=Math.floor(value%3600/60),s=value%60;return h?`${h}:${String(m).padStart(2,'0')}:${String(s).padStart(2,'0')}`:`${m}:${String(s).padStart(2,'0')}`;}
function showError(message){document.querySelector('#stage').innerHTML=`<div class="preparing"><h1>Playback unavailable</h1><p>${escapeHTML(message)}</p></div>`;}
async function stop(){if(stopped)return;stopped=true;clearTimeout(pollTimer);await sendScrobble('stop');if(session)await fetch(`/api/stream/${encodeURIComponent(session)}`,{method:'DELETE'}).catch(()=>{});location.href='/';}document.querySelector('#stop').addEventListener('click',stop);document.querySelector('#back').addEventListener('click',event=>{event.preventDefault();stop()});
function escapeHTML(value){return String(value??'').replace(/[&<>'"]/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[char]))}
