const params=new URLSearchParams(location.search);const session=params.get('session');const title=params.get('title')||'Unarr player';let pollTimer=null,stopped=false,total=0;document.querySelector('#title').textContent=title;
if(!session){showError('No stream session was provided.')}else{poll();}
async function poll(){try{const response=await fetch(`/api/stream/${encodeURIComponent(session)}`,{cache:'no-store'});const data=await response.json();if(!response.ok)throw new Error(data.error);total=Number(data.durationSeconds)||0;if(data.status==='ready'&&data.url){openVideo(data);return}if(data.status==='error')throw new Error(data.error||'Stream failed.');if(data.status==='stopped')throw new Error('The stream stopped before playback was ready.');showProgress(data);pollTimer=setTimeout(poll,1000);}catch(error){showError(error.message);}}
function showProgress(data){const elapsed=Number(data.elapsedSeconds)||0;const timeout=Number(data.metadataTimeoutSeconds)||60;const metadata=data.phase==='metadata';const percent=metadata?Math.min(100,elapsed/timeout*100):(Number(data.progress)||4);document.querySelector('#state').textContent=data.message||'Preparing stream…';document.querySelector('#detail').textContent=metadata?`Waiting for metadata: ${elapsed}s of ${timeout}s`:phaseLabel(data.phase,elapsed);document.querySelector('#bar').style.width=`${percent}%`;document.querySelector('#runtime').textContent=`00:00 / ${formatTime(total)}`;}
function phaseLabel(phase,elapsed){return {buffering:`Building playback buffer · ${elapsed}s`,transcoding:`Encoding browser-compatible video · ${elapsed}s`,streaming:`Downloading and preparing playback · ${elapsed}s`}[phase]||`Preparing · ${elapsed}s`;}
function openVideo(data){const tracks=(data.tracks||[]).map(track=>`<track kind="${escapeHTML(track.kind)}" src="${escapeHTML(track.src)}" srclang="${escapeHTML(track.srclang)}" label="${escapeHTML(track.label)}" ${track.default?'default':''}>`).join('');document.querySelector('#stage').innerHTML=`<video controls autoplay playsinline src="${escapeHTML(data.url)}">${tracks}</video>`;const video=document.querySelector('video');const audio=data.audio;document.querySelector('#track').textContent=audio?[audio.lang?.toUpperCase(),audio.title,audio.codec].filter(Boolean).join(' · '):'HLS player';video.addEventListener('loadedmetadata',()=>{if(!total&&Number.isFinite(video.duration))total=video.duration;updateRuntime(video)});video.addEventListener('timeupdate',()=>updateRuntime(video));}
function updateRuntime(video){document.querySelector('#runtime').textContent=`${formatTime(video.currentTime)} / ${formatTime(total||video.duration)}`;}
function formatTime(seconds){if(!Number.isFinite(seconds)||seconds<=0)return'--:--';const value=Math.round(seconds);const h=Math.floor(value/3600),m=Math.floor(value%3600/60),s=value%60;return h?`${h}:${String(m).padStart(2,'0')}:${String(s).padStart(2,'0')}`:`${m}:${String(s).padStart(2,'0')}`;}
function showError(message){document.querySelector('#stage').innerHTML=`<div class="preparing"><h1>Playback unavailable</h1><p>${escapeHTML(message)}</p></div>`;}
async function stop(){if(stopped)return;stopped=true;clearTimeout(pollTimer);await fetch(`/api/stream/${encodeURIComponent(session)}`,{method:'DELETE'}).catch(()=>{});location.href='/';}document.querySelector('#stop').addEventListener('click',stop);document.querySelector('#back').addEventListener('click',event=>{event.preventDefault();stop()});
function escapeHTML(value){return String(value??'').replace(/[&<>'"]/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[char]))}
