const params=new URLSearchParams(location.search);const session=params.get('session'),externalUrl=params.get('url');const title=params.get('title')||'Unarr player';const trakt={type:params.get('traktType'),traktId:Number(params.get('traktId'))||0,season:Number(params.get('season'))||0,episode:Number(params.get('episode'))||0};let pollTimer=null,stopped=false,total=0,lastScrobble=0,currentVideo=null;document.querySelector('#title').textContent=title;
if(externalUrl){openVideo({url:externalUrl});}else if(!session){showError('No stream source was provided.')}else{poll();}
async function poll(){try{const response=await fetch(`/api/stream/${encodeURIComponent(session)}`,{cache:'no-store'});const data=await response.json();if(!response.ok)throw new Error(data.error);total=Number(data.durationSeconds)||0;if(data.status==='selecting'){showTrackSelection(data);return}if(data.status==='ready'&&data.url){openVideo(data);return}if(data.status==='error')throw new Error(data.error||'Stream failed.');if(data.status==='stopped')throw new Error('The stream stopped before playback was ready.');showProgress(data);pollTimer=setTimeout(poll,1000);}catch(error){showError(error.message);}}
function showTrackSelection(data){const audio=data.availableAudio||[],subtitles=data.availableSubtitles||[];const options=(items,prefix)=>items.map((track,index)=>`<option value="${index}" ${track.default?'selected':''}>${escapeHTML(trackName(track,index,prefix))}</option>`).join('');document.querySelector('#stage').innerHTML='<div class="preparing"><h1>Ready to play</h1><p>Select playback tracks below.</p></div>';const controls=document.querySelector('#track-controls');controls.hidden=false;controls.innerHTML=`<form id="track-form"><label>Audio<select id="audio-select">${options(audio,'Audio')}</select></label><label>Subtitles<select id="subtitle-select"><option value="-1">Off</option>${options(subtitles,'Subtitle')}</select></label><button>Start playback</button></form>`;document.querySelector('#track-form').addEventListener('submit',startSelectedTracks)}
function trackName(track,index,prefix){return [track.lang&&track.lang.toUpperCase(),track.title,track.codec,track.channels&&`${track.channels}ch`].filter(Boolean).join(' · ')||`${prefix} ${index+1}`}
async function startSelectedTracks(event){event.preventDefault();const button=event.currentTarget.querySelector('button');button.disabled=true;try{const response=await fetch('/api/stream/tracks',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({sessionId:session,audioIndex:Number(document.querySelector('#audio-select').value||0),subtitleIndex:Number(document.querySelector('#subtitle-select').value??-1)})});const data=await response.json();if(!response.ok)throw new Error(data.error);document.querySelector('#track-controls').hidden=true;document.querySelector('#stage').innerHTML='<div class="preparing"><i></i><h1 id="state">Preparing selected tracks…</h1><p id="detail">Starting HLS playback.</p><div class="bar"><span id="bar"></span></div></div>';poll()}catch(error){button.disabled=false;alert(error.message)}}
function showProgress(data){const elapsed=Number(data.elapsedSeconds)||0;const timeout=Number(data.metadataTimeoutSeconds)||60;const metadata=data.phase==='metadata';const percent=metadata?Math.min(100,elapsed/timeout*100):(Number(data.progress)||4);document.querySelector('#state').textContent=data.message||'Preparing stream…';document.querySelector('#detail').textContent=metadata?`Waiting for metadata: ${elapsed}s of ${timeout}s`:phaseLabel(data.phase,elapsed);document.querySelector('#bar').style.width=`${percent}%`;document.querySelector('#runtime').textContent=`00:00 / ${formatTime(total)}`;}
function phaseLabel(phase,elapsed){return {buffering:`Building playback buffer · ${elapsed}s`,transcoding:`Encoding browser-compatible video · ${elapsed}s`,streaming:`Downloading and preparing playback · ${elapsed}s`}[phase]||`Preparing · ${elapsed}s`;}
function openVideo(data){const tracks=(data.tracks||[]).map(track=>`<track kind="${escapeHTML(track.kind)}" src="${escapeHTML(track.src)}" srclang="${escapeHTML(track.srclang)}" label="${escapeHTML(track.label)}" ${track.default?'default':''}>`).join('');document.querySelector('#stage').innerHTML=`<video controls autoplay playsinline src="${escapeHTML(data.url)}">${tracks}</video>`;const video=document.querySelector('video');currentVideo=video;const audio=data.audio;document.querySelector('#track').textContent=audio?[audio.lang?.toUpperCase(),audio.title,audio.codec].filter(Boolean).join(' · '):'HLS player';video.addEventListener('loadedmetadata',()=>{if(!total&&Number.isFinite(video.duration))total=video.duration;updateRuntime(video)});video.addEventListener('play',()=>sendScrobble('start'));video.addEventListener('pause',()=>{if(!video.ended)sendScrobble('pause')});video.addEventListener('ended',()=>sendScrobble('stop',100));video.addEventListener('timeupdate',()=>{updateRuntime(video);if(Date.now()-lastScrobble>30000)sendScrobble('start')});}
function playbackProgress(){if(!currentVideo)return 0;const duration=total||currentVideo.duration;return Number.isFinite(duration)&&duration>0?Math.max(0,Math.min(100,currentVideo.currentTime/duration*100)):0}
async function sendScrobble(action,forcedProgress){if(!trakt.traktId||!['movie','show'].includes(trakt.type))return;lastScrobble=Date.now();const body={action,type:trakt.type,traktId:trakt.traktId,progress:forcedProgress??playbackProgress()};if(trakt.type==='show'){body.season=trakt.season;body.episode=trakt.episode}try{await fetch('/api/trakt/scrobble',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body),keepalive:action==='stop'})}catch(error){}}
function updateRuntime(video){document.querySelector('#runtime').textContent=`${formatTime(video.currentTime)} / ${formatTime(total||video.duration)}`;}
function formatTime(seconds){if(!Number.isFinite(seconds)||seconds<=0)return'--:--';const value=Math.round(seconds);const h=Math.floor(value/3600),m=Math.floor(value%3600/60),s=value%60;return h?`${h}:${String(m).padStart(2,'0')}:${String(s).padStart(2,'0')}`:`${m}:${String(s).padStart(2,'0')}`;}
function showError(message){document.querySelector('#stage').innerHTML=`<div class="preparing"><h1>Playback unavailable</h1><p>${escapeHTML(message)}</p></div>`;}
async function stop(){if(stopped)return;stopped=true;clearTimeout(pollTimer);await sendScrobble('stop');if(session)await fetch(`/api/stream/${encodeURIComponent(session)}`,{method:'DELETE'}).catch(()=>{});location.href='/';}document.querySelector('#stop').addEventListener('click',stop);document.querySelector('#back').addEventListener('click',event=>{event.preventDefault();stop()});
function escapeHTML(value){return String(value??'').replace(/[&<>'"]/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[char]))}
